# Generated by Django 4.0.2 on 2022-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('hemoglobin', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
            ],
        ),
    ]
