# Generated by Django 4.0.2 on 2022-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemodonor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
