# Generated by Django 4.0.2 on 2022-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemodonor', '0003_alter_donor_data_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor_data',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='donor_data',
            name='donation_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor_data',
            name='gender',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
