# Generated by Django 4.0.2 on 2022-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemodonor', '0004_rename_name_donor_data_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
