# Generated by Django 4.0.2 on 2022-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemodonor', '0005_alter_donor_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
